name: Generate Allure Report

on:
  push:
    branches:
      - master  # Run workflow on pushing to `master` branch

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2. Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 3. Run Playwright tests
      - name: Run tests with Playwright
        run: npx playwright test

      # Step 4. Generate Allure report
      - name: Generate Allure report
        run: |
          mkdir -p allure-report # Ensure the folder exists
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      # Step 5. Checkout the report branch
      - name: Checkout report branch
        uses: actions/checkout@v3
        with:
          ref: report-branch

      # Step 6. Commit and push the generated report
      - name: Push report to branch
        run: |
          rm -rf *
          mv allure-report/* .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Allure report" || echo "No changes to commit"
          git push -f origin report-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7. Publish GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report-branch # Branch where the report is pushed
          publish_dir: . # Directory to deploy

      # Step 8. Output link to GitHub Pages
      - name: Set GitHub Pages URL
        run: echo "Allure Report available at: https://Maximka47.github.io/PlaywrightTestTask/"
