name: Generate Allure Report

on:
  push:
    branches:
      - master  # Ensure this matches your main branch name

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: timeout 5m npm ci && npx playwright install --with-deps && npm install -D allure-playwright

      # Step 3: Run Playwright tests and generate allure-results
      - name: Run tests with Playwright
        run: npx playwright test --reporter=allure-playwright

      # Step 4: Generate Allure report
      - name: Generate Allure report
        run: |
          if [ -d "allure-results" ]; then
            npm install -g allure-commandline
            allure generate allure-results --clean -o allure-report
          else
            echo "No allure-results directory found. Tests may have failed."
            exit 1
          fi

      # Step 5: Move Allure report files to a temporary folder (to save them)
      - name: Save Allure Report files
        run: |
          echo "Saving Allure report to a temporary location..."
          mkdir -p /tmp/allure-report
          cp -R allure-report/* /tmp/allure-report/

      # Step 6: Prepare report branch
      - name: Prepare report branch
        run: |
          git fetch origin
          git reset --hard
          git clean -fd
          if git ls-remote --exit-code --heads origin report-branch; then
            git checkout report-branch
            git pull origin report-branch
          else
            git checkout --orphan report-branch
            git rm -rf .
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Restore Allure Report files to the working directory
      - name: Restore Allure Report files
        run: |
          echo "Restoring Allure report files..."
          cp -R /tmp/allure-report/* .

      # Step 8: Commit and push the generated Allure report
      - name: Push report to branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Allure report" || echo "No changes to commit"
          git push origin report-branch --force

      # Step 9: Deploy Allure Report to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report-branch
          publish_dir: .

      # Step 10: Output GitHub Pages public link
      - name: Set GitHub Pages URL
        run: |
          echo "Allure Report available at: https://Maximka47.github.io/PlaywrightTestTask/"