name: Generate Allure Report

on:
  push:
    branches:
      - master  # Ensure this matches your main branch name

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps

      # Step 3: Run Playwright tests
      - name: Run tests with Playwright
        run: npx playwright test

      # Step 4: Generate Allure report
      - name: Generate Allure report
        run: |
          if [ -d "allure-results" ]; then
            npm install -g allure-commandline
            allure generate allure-results --clean -o allure-report
          else
            echo "No allure-results directory found. Tests may have failed."
            exit 1
          fi

      # Step 5: Clean any uncommitted changes and checkout the report branch
      - name: Prepare report branch
        run: |
          git fetch origin
          # Clean uncommitted changes to avoid checkout conflicts
          git reset --hard
          git clean -fd
          if git ls-remote --exit-code --heads origin report-branch; then
            git checkout report-branch
            git pull origin report-branch
          else
            git checkout --orphan report-branch
            git rm -rf .
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Commit and push the generated Allure report
      - name: Push report to branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Remove old files (except .git directory) and add new report
          find . -not -name '.git' -delete
          mv allure-report/* .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Allure report" || echo "No changes to commit"
          git push origin report-branch --force

      # Step 7: Deploy Allure Report to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report-branch
          publish_dir: .

      # Step 8: Output GitHub Pages public link
      - name: Set GitHub Pages URL
        run: |
          echo "Allure Report available at: https://Maximka47.github.io/PlaywrightTestTask/"